version: '2'
services:
  firsttry-app:
    image: firsttry
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://firsttry-postgresql:5432/firsttry
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  firsttry-postgresql:
    extends:
      file: postgresql.yml
      service: firsttry-postgresql
