version: '2'
services:
  firsttry-postgresql:
    image: postgres:11.2
    # volumes:
    #     - ~/volumes/jhipster/firsttry/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=firsttry
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
